"""add_unique_constraint_meta_gastos

Revision ID: 39bfb3faafbb
Revises: ab001bd0741f
Create Date: 2026-03-31 19:26:33.255902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bfb3faafbb'
down_revision: Union[str, Sequence[str], None] = 'ab001bd0741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controle_financeiro')
    with op.batch_alter_table('meta_gastos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_usuario_categoria_mes', ['id_usuario', 'categoria', 'data_mes'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_gastos', schema=None) as batch_op:
        batch_op.drop_constraint('uix_usuario_categoria_mes', type_='unique')

    op.create_table('controle_financeiro',
    sa.Column('id_gasto', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.TEXT(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('categoria', sa.TEXT(), nullable=False),
    sa.Column('metodo_pagamento', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    # ### end Alembic commands ###
