"""Criando tabela para meta de gastos mensais

Revision ID: ab001bd0741f
Revises: c2d089301c94
Create Date: 2026-03-31 16:28:13.864577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ab001bd0741f'
down_revision: Union[str, Sequence[str], None] = 'c2d089301c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_gastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('data_mes', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agno_schema_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_agno_schema_versions_created_at'))

    op.drop_table('agno_schema_versions')
    op.drop_table('controle_financeiro')
    with op.batch_alter_table('agno_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_agno_sessions_created_at'))
        batch_op.drop_index(batch_op.f('idx_agno_sessions_session_type'))

    op.drop_table('agno_sessions')
    with op.batch_alter_table('financas', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financas', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('agno_sessions',
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('session_type', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('team_id', sa.VARCHAR(), nullable=True),
    sa.Column('workflow_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('session_data', sqlite.JSON(), nullable=True),
    sa.Column('agent_data', sqlite.JSON(), nullable=True),
    sa.Column('team_data', sqlite.JSON(), nullable=True),
    sa.Column('workflow_data', sqlite.JSON(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('runs', sqlite.JSON(), nullable=True),
    sa.Column('summary', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('agno_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_agno_sessions_session_type'), ['session_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_agno_sessions_created_at'), ['created_at'], unique=False)

    op.create_table('controle_financeiro',
    sa.Column('id_gasto', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.TEXT(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('categoria', sa.TEXT(), nullable=False),
    sa.Column('metodo_pagamento', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_table('agno_schema_versions',
    sa.Column('table_name', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('table_name')
    )
    with op.batch_alter_table('agno_schema_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_agno_schema_versions_created_at'), ['created_at'], unique=False)

    op.drop_table('meta_gastos')
    # ### end Alembic commands ###
